name: pepseqpred
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip

  # GPU-enabled PyTorch
  - pytorch=2.4.*
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio

  # data science/ML stack
  - numpy=2.3.4
  - pandas=2.3.3
  - optuna>=3.5
  - scipy
  - scikit-learn
  - networkx=3.5
  - mpmath=1.3.0
  - psutil
  - tqdm

  # Jupyter ecosystem
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - traitlets
  - pygments
  - prompt_toolkit
  - stack_data
  - parso
  - jedi
  - decorator
  - tornado
  - pyzmq
  - nest-asyncio
  - typing_extensions

  # plotting
  - matplotlib-inline

  # bio ML and ESM
  - biopython

  # pip only dependencies
  - pip:
      - fair-esm==2.0.0
      - colorama==0.4.6
      - asttokens==3.0.0
      - comm==0.2.3
      - ipython_pygments_lexers==1.1.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - Jinja2==3.1.6
      - MarkupSafe==3.0.3
      - packaging==25.0
      - platformdirs==4.5.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - setuptools==80.9.0
      - six==1.17.0
      - sympy==1.14.0
      - tzdata==2025.2
      - wcwidth==0.2.14
